### ISSUE TITLE
All datasets should start zoomed in on CONUS in exploration

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#21]
We expect the focus of the U.S. GHG Center users always to be on contiguous United States (CONUS).

Therefore, all dataset views in the exploration should start zoomed in on the CONUS region (or narrower), even if the dataset has larger / global extent.

Currently, most datasets start on global extent. Does this setting come from STAC or MDX dataset config files? Do the dataset config files already support overriding the initial extent / bounding box / center + zoom level?

## Acceptance criteria

- [ ] All datasets that cover CONUS or parts of it start zoomed in on that

**Comment by danielfdsilva** [comment]
The zoom is set based on the dataset extend from the STAC record.

For example, the [Methane emissions datasets](https://ghg-demo.netlify.app/data-catalog/epa-emissions-annual-tests/explore), have a CONUS extent and are zoomed in upon load.

It is currently not possible to override the initial bounding box, but it is something that could be explored.

The map position is first derived from the url (this need be for sharing purposes), and if there isn't a position set, we use the value from the STAC record. An implementation option would be to check for a default bounding box (set on the dataset file) instead of STAC, and only default to the latter if the dataset file doesn't have anything set.

**Comment by j08lue** [comment]
> An implementation option would be to check for a default bounding box (set on the dataset file) instead of STAC, and only default to the latter if the dataset file doesn't have anything set.

That would be great and a valuable feature enabling users to explore data in the right context for the particular instance / thematic context.

We discussed just today that we should keep the Exploration & Analysis rather generic - less context-heavy - but this particular feature would still be within scope, I think.

So please go forward with implementing that override, @danielfdsilva (pls feel free to delegate).
