### ISSUE TITLE
Release Exploration & Analysis in its current state for EIC and GHG Center?

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#221]
Yesterday (Monday) @faustoperez and @j08lue (accompanied by @hanbyul-here and @danielfdsilva) conducted four 30-minute user testing sessions for the Exploration & Analysis interface with scientists.

- https://github.com/NASA-IMPACT/veda-ui/issues/740

We gathered great insights about how the scientists approach the interface, what they find particularly valuable or nicely done and where there are challenges. These insights will feed into fast cycles of improvements and more testing in the coming weeks and months.

## Could we release now?

Overall, our impression was that the interface is usable and useful. 

## Issues blocking release

The only blocking issue we identified was

- https://github.com/NASA-IMPACT/veda-ui/issues/747

And additional ongoing work also needs to be complete

- [ ] https://github.com/NASA-IMPACT/veda-ui/issues/746
- [ ] https://github.com/NASA-IMPACT/veda-architecture/issues/334
- [ ] Missing integration with dataset overview pages - happening in https://github.com/NASA-IMPACT/veda-ui/pull/751
- [ ] Missing integration into top nav - happening in https://github.com/NASA-IMPACT/veda-ui/pull/751
- [ ] https://github.com/NASA-IMPACT/veda-ui/issues/724
- [ ] https://github.com/NASA-IMPACT/veda-ui/pull/744 merged + propagated to E&A

## Risks

1. There could be bugs or performance issues we have not yet identified causing a things to fail when users engage with the interface 
    Possible mitigation: We would need to do a lot of stress testing ahead of the release this/next week.
2. There is still some work to do - we might not get done
    Possible mitigation: We can always choose not to merge this feature anyways and keep the current UI.

## Acceptance criteria

- [x] Decided whether whether we should release the interface in its current state for the GHG Center and EIC, being aware of the risks

**Comment by deborahUAH** [comment]
After careful review, I suggest not deploying to GHG Center. 
Here are some concerns that need to be addressed

- should not say "select a dataset" but rather one is selecting a _data layer_
- not clear anymore how a user looking at a dataset in the data catalog can view the data  - the user workflow isn't clear unless the dataset landing page has a link to explore and it defaults to the layers for that dataset??
- the alt button select doesn't work as described in the intro teachings
- a thicker line is needed separating the ...
- if I remove an AOI, the plotted time series should also go since now I can see them but I no longer know which data the lines are constructed from.
- I should be able to select all the layers for a dataset easily.  Right now to have the flexibility of switching between the many layers of EPA dataset I would need to select them all from the lengthy list of data layers.  Lots of unnecessary clicks if there were only a way to select datasets and then choose layers wanted in the explore environment
- what will happen to dataset specific defaults set previously when we switch to the new environment? (ie. projection, background, etc?
- I can't display EPA data? then how will I look at it (the main point)
- what happened to GIS links (XYZ, WMTS)? I don't see a way to get to this information?

Happy to meet to go over these concerns.  Might be good for me to have a testing session with the team?

**Comment by j08lue** [comment]
We made the call today not to release E&A on the GHG Center and EIC instances before the upcoming official release.

However, we should keep the pace and aim for a deploy on the VEDA Dashboard as soon as possible, if possible before the GHG Center launch, so it can serve as a reference for the upcoming changes for GHGC/EIC.

**Comment by j08lue** [comment]
Building a new release plan in

- https://github.com/NASA-IMPACT/veda-ui/issues/763
