### ISSUE TITLE
Investigate critical error view stats

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#249]
GHG Center site analytics from 5 December (public launch spike) show that, some of the ~700 visitors, in total encountered "Critical Error" failures 10 times: 

![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/86323b1e-b819-45ec-8109-f7cbbe2caeab)

Are these stats reliable? If so, is there any way we can get to the cause?

## Acceptance criteria

- [x] Investigated and opened ticket for further action, if required

**Comment by j08lue** [comment]
We have earlier seen Critical Error's in Exploration when datasets where missing summaries (in STAC collection metadata).

- https://github.com/NASA-IMPACT/veda-config/issues/353

I tried "Exploration" on all datasets in https://earth.gov/ghgcenter/data-catalog (that had raster layers), testing many sub-layers, but all worked. 🤷

**Comment by aboydnw** [comment]
Here are a couple screenshots I pulled from analytics. 

The first, is a [report ](https://lookerstudio.google.com/reporting/cdc62361-9bf4-4532-820e-a34d365d5017)that shows some information on the critical errors. Most of them are happening on the home page, but there's a few other stragglers. I don't know if this means there is something wrong with the home page or if it has the most errors because it has WAY more traffic than any other page. In fact, it might be a sign that the home page is more performant than other pages because it has like 100x as many views as the Analysis page, which is also on the list.
<img width="761" alt="Untitled Report › Untitled Page 2023-12-07 12-30-54" src="https://github.com/NASA-IMPACT/veda-config-ghg/assets/92742765/7cf2d3bc-fdad-4c02-a4d5-64ebc1451f73">

The second, is a path exploration in google analytics. This shows that almost all of the critical errors are happening when the land for the first time or after the first click. Again, I'm not sure if this is definitive because we don't have high engagement from people. Users drop off pretty quickly.
<img width="847" alt="Analytics 2023-12-07 12-26-13" src="https://github.com/NASA-IMPACT/veda-config-ghg/assets/92742765/589aba15-c0e7-45cb-85be-4cb42c26d3b9">

**Comment by aboydnw** [comment]
I posted this in slack but also sharing here: 
30 critical errors represents ~1.2% of overall traffic

We should consider that with the effort we put towards this ticket

**Comment by j08lue** [comment]
We addressed this in the following ways:
1. Improving the wording and UX of the formerly called "critical error" page, which is now much less alarming and tells users what they can do
2. Continuing to monitor this - the error has been absent recently, it seems
