### ISSUE TITLE
Add News/Announcements/Events Static Content page for GHG Center

### ISSUE THREAD

**Issue by deborahUAH** [NASA-IMPACT/veda-config-ghg#252]
The HQ Comms folks want a Learn page for GHG Center.  This will require the following actions
- [ ] add Learn to the navigation bar the directs users to the page
- [ ] Create a static page (like the About page)  that can be filled with content
- [ ] Page should have nav bar and footer content
- [ ] Page needs the following subsections and a means for a user to jump to the subsections from the top of the page or from the Learn 
- [ ] The content for the page is currently being drafted at https://docs.google.com/document/d/1CMmSBBqvQfmRBw0sFaTaZTyd8QF6wh7fx_6OhukWcHM  when complete and approved, will be ready to be added to page
- [ ] the page is expected to be frequently updated with new content. Would be better if easy for comms team to do.  Process for updates needs to be outlined
- [ ] page is reviewed by requesters and once satisfactory and tested can be pushed to production

Time frame for release is rapid - need asap.

**Comment by hanbyul-here** [comment]
This page has a whole structure that we need design help. Tagging @faustoperez  I see some expectations for interactive elements on the google doc. I suggest to start with static pages, and add it as it is necessary especially if this page needs to be launched by the end of this week.

As stated, the page looks like it needs an update often, otherwise it will look outdated. Is there a point person in charge of updating the content in the future? Are they already familiar with VEDA workflow?

**Comment by faustoperez** [comment]
We are having a look from a design perspective and will report back!
