### ISSUE TITLE
Legend is messed up in new stories

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-config-ghg#269]
# Description
I noticed that legends are messed up in this temporary story i'm creating for the ams workshop - PR here - https://github.com/NASA-IMPACT/veda-config-ghg/pull/267

Preview link where the issue is: https://deploy-preview-267--ghg-demo.netlify.app/stories/ams-workshop-story

The weirdest thing tho, is in the same preview link, legends in this other story are fine - https://deploy-preview-267--ghg-demo.netlify.app/stories/us-methane-sources

Help me figure out what's going on!

Would like this figured out by this weekend, the workshop is on Sunday.

@hanbyul-here @sandrahoang686 @j08lue

**Comment by j08lue** [comment]
I see what you mean:

[broken style](https://deploy-preview-267--ghg-demo.netlify.app/stories/ams-workshop-story):
![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/ad0cdbac-2fca-4306-98bb-2d6abacf2dcc)

[working style](https://deploy-preview-267--ghg-demo.netlify.app/stories/us-methane-sources):
![image](https://github.com/NASA-IMPACT/veda-config-ghg/assets/3404817/b55f8ab1-b399-423c-85e4-43bf050850c5)

The issue seems to be that the wrong style gets applied to the legend title.

**Comment by j08lue** [comment]
The difference seems to be that you are doing `<Block><Prose><Figure><Map>`, while the other working one has just `<Block><Figure><Map>` (i.e. not wrapped in `Prose`).

**Comment by j08lue** [comment]
I fixed it on your PR - hope this is how you meant the content to look. Btw, you can use the "experimental" live MDX editor while writing and debugging your content: https://deploy-preview-267--ghg-demo.netlify.app/sandbox/mdxeditor

You just need to copy-paste your MDX in and out of the editor manually.

**Comment by slesaad** [comment]
oooh! great catch! thanks @j08lue 🙇
