### ISSUE TITLE
Add uncertainty and grade specifications to GHG datasets

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-ghg#49]
We now have a feature in VEDA UI to specify uncertainty and grade to be displayed on Dataset cards. https://github.com/NASA-IMPACT/veda-ui/pull/629

We just need to add this information to the dataset config files - see details in the [docs](https://github.com/NASA-IMPACT/veda-ui/blob/3bebf332491fd06ccbda72c72da4c5522daf2f2b/docs/content/TAXONOMY.md#specific-taxonomies).

```
Uncertainty: Degree of uncertainty of this dataset
- High
- Medium
- Low

Grade: What the dataset is suitable for / its grade
- Research
- Agency standard/regulatory
```

## Acceptance criteria

- [ ] All GHG datasets have `uncertainty` and `grade` taxonomy specified

**Comment by Jeanne-le-Roux** [comment]
@j08lue @siddharth0248 I'll double check to see if this is something we want to add for R1. We are indicating on the dataset overview page whether the data is research, regulatory, or operational, but have held off on an uncertainty label since there may be some opinions & it is part of a broader discussion. We did add a 'dataset accuracy' section on the overview page where uncertainties can be described free-form. Regardless, it's good to know that this type of label will be easy to add. Can I see the icons that have been assigned to each value?

**Comment by j08lue** [comment]
> We are indicating on the dataset overview page whether the data is research, regulatory, or operational

Nice, so we have that information already. Should we add that to the configuration, then that icon would already appear? We can wait with adding the uncertainty / accuracy information.

> Can I see the icons that have been assigned to each value?

Yes, they are documented here: https://github.com/NASA-IMPACT/veda-ui/blob/3bebf332491fd06ccbda72c72da4c5522daf2f2b/docs/content/TAXONOMY.md#specific-taxonomies

Please let us know if any adjustment is needed.

**Comment by Jeanne-le-Roux** [comment]
We'll address this after R1.

**Comment by j08lue** [comment]
Trust this to come up anew if need be - closing for now.
